# Generated by Django 3.1.5 on 2021-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredTextBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
            ],
        ),
    ]
