# Generated by Django 3.1.5 on 2021-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=120)),
                ('daysOfWeek', models.TextField()),
                ('time', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
