# Generated by Django 3.1.5 on 2021-01-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='daysOfWeek',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='location',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='time',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='instructor',
            name='office',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
