# Generated by Django 3.1.5 on 2021-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=30)),
                ('coursenumber', models.IntegerField()),
                ('coursename', models.CharField(max_length=30)),
                ('coursehours', models.CharField(max_length=30)),
                ('academiccredit', models.IntegerField()),
                ('calendarref', models.URLField()),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
