# Generated by Django 3.1.5 on 2021-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='description',
            new_name='daysOfWeek',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='title',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='completed',
        ),
        migrations.AddField(
            model_name='timetable',
            name='location',
            field=models.TextField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TextField(default=234),
            preserve_default=False,
        ),
    ]
